[package]
name = "bitrw"
version = "0.6.0"
authors = ["Sergey Shandar"]
description = "Bit Read/Write"
license = "Apache-2.0"
repository = "https://github.com/rust-common/bitrw"

[dependencies]
base2 = "^0.2.2"
int = "^0.2.10"
