[package]
name = "bitrw"
version = "0.7.1"
authors = ["Sergey Shandar"]
description = "Bit Read/Write"
license = "Apache-2.0"
repository = "https://github.com/rust-common/bitrw"

[dependencies]
base2 = "^0.3.0"
int = "^0.2.11"
