[package]
name = "bitrw"
version = "0.8.3"
authors = ["Sergey Shandar"]
description = "Bit Read/Write"
license = "Apache-2.0"
repository = "https://github.com/rust-common/bitrw"

[dependencies]
base2 = "^0.3.1"
int = "^0.3.0"
